# Generated by Django 2.0.1 on 2018-01-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0003_section_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('download_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField()),
                ('unit', models.CharField(choices=[(0, 'level'), (1, 'discharge')], max_length=1)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivers.Gauge')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='gauge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rivers.Gauge'),
        ),
    ]
