# Generated by Django 2.0.1 on 2018-01-12 22:19

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0008_auto_20180112_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='markdown',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='minimum',
            field=models.FloatField(null=True),
        ),
    ]
