# Generated by Django 2.0.1 on 2018-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0015_auto_20180124_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
