# Generated by Django 2.0.1 on 2018-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0016_point_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='url_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='url_id',
            field=models.IntegerField(null=True),
        ),
    ]
