# Generated by Django 2.0.1 on 2018-02-06 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0019_section_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='gauge',
        ),
        migrations.AddField(
            model_name='gauge',
            name='get_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='river',
            name='gauge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rivers.Gauge'),
        ),
        migrations.AddField(
            model_name='river',
            name='level_gauge',
            field=models.BooleanField(default=True),
        ),
    ]
