# Generated by Django 2.0.1 on 2018-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_url', models.URLField()),
                ('river_id', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('minimum', models.FloatField()),
            ],
        ),
    ]
