# Generated by Django 2.0.1 on 2018-01-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0004_auto_20180111_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
    ]
