# Generated by Django 2.0.1 on 2018-01-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0005_auto_20180111_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
