# Generated by Django 2.0.1 on 2018-01-12 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rivers', '0007_auto_20180111_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivers.Gauge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='creation_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.CharField(default='4', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='last_edit_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='markdown',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='recent_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
