# Generated by Django 2.0.1 on 2018-01-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0010_auto_20180112_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[(0, 'Take out'), (1, 'Put in'), (2, 'Rapid'), (3, 'Point of interest')], max_length=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longditude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Sectionpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivers.Points')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivers.Section')),
            ],
        ),
    ]
