# Generated by Django 2.0.1 on 2018-01-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0012_auto_20180124_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
    ]
