# Generated by Django 2.0.1 on 2018-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0017_auto_20180130_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
