# Generated by Django 2.0.1 on 2018-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0018_auto_20180203_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
